services:
  surveillance.carpha_report_service:
    class: DIISH\SComDisBundle\Service\CARPHAReportService
    arguments:
      - @doctrine
  surveillance.dailly_tally_report_service:
    class: DIISH\SComDisBundle\Service\DailyTallyReportService
    arguments:
      - @doctrine
  surveillance.chart_service:
    class: DIISH\SComDisBundle\Service\ChartService
    arguments:
      - @doctrine
  surveillance.dailly_tally_import_service:
    class: DIISH\SComDisBundle\Service\DailyTallyImportService
    arguments:
      - @doctrine
  surveillance.epidemic_phase_service:
    class: DIISH\SComDisBundle\Service\EpidemicPhaseService
    arguments:
      - @doctrine
  log_service:
    class: DIISH\SComDisBundle\Service\LogService
    arguments:
      - @doctrine