homepage:
    pattern: /
    defaults: { _controller: DIISHCommonBundle:Default:index }

diishs_com_dis:
    resource: "@DIISHSComDisBundle/Controller/"
    type:     annotation
    prefix:   /

diish_common:
    resource: "@DIISHCommonBundle/Controller/"
    type:     annotation
    prefix:   /

imag_ldap:
    resource: "@IMAGLdapBundle/Resources/config/routing.yml"